version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    command: ["clickhouse-server", "--", "--listen_host=0.0.0.0"]
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data: 