version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123" # HTTP interface - access /play for testing
      - "9000:9000" # Native interface
    command:
      [
        "clickhouse-server",
        "--",
        "--listen_host=0.0.0.0",
        "--config-file=/etc/clickhouse-server/config.xml",
      ]
    env_file:
      - .env
    volumes:
      - ./data/clickhouse/:/var/lib/clickhouse/
      - ./clickhouse-config/users.d/:/etc/clickhouse-server/users.d/
      - ./clickhouse-logs/:/var/log/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  dashboard_database:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/

volumes:
  clickhouse_data:
