name: Tests Action
run-name: Tests
on: [push]
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install
      - name: Running unit tests
        run: |
          cd ${{ github.workspace }}
          pnpm run unit-tests
